### ISSUE TITLE
etnx & etnxp mining

### ISSUE THREAD

**Issue by Miner1305** [Bendr0id/xmrigCC#228]
etnx & etnxp mining issue, the algo changes to fast2 instead of msr.

**Comment by Bendr0id** [comment]
In the next release you can use "forcePowVariant" : true, to overrule autodetection. That should solve your issue.

**Comment by Bendr0id** [comment]
Fixed in XMRigCC 1.8.12

https://github.com/Bendr0id/xmrigCC/releases/tag/1.8.12

# 1.8.12
- Fixed "force-pow-variant" overrules autodetect for XTLv9/Fast2 #228
- Fixed out of source building (asm code generator)
- Fixed gcc 8 builds (self check failed), for msys2 make sure you update xmrigcc-deps #218
- CN-Ultralite/turtle is shown correctly on the Dashboard

**Comment by Miner1305** [comment]
still not working
specified "variant":msr"  and "forcePowVariant" : true tried all combinations, but still its same going to fast2

**Comment by Bendr0id** [comment]
Hmm. I tested it with 1.8.12.

Do you used that one too? 

Which pool are you using?

Please join the discord, so we can chat much easier.

**Comment by Bendr0id** [comment]
```
[2019-02-10 10:24:40] cryptonight hash self-test
[2019-02-10 10:24:40] cryptonight hash self-test... successful.
 * VERSIONS:     XMRigCC/1.8.12 (based on XMRig) libuv/1.24.0 gcc/7.3.0 (RELEASE with TLS)
 * CPU:          Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz (1) x64 AES-NI ASM-INTEL
 * CPU L2/L3:    1.0 MB/8.0 MB
 * THREADS:      4, cryptonight, hf=1, donate=1%, affinity=auto
 * POOL #1:      pool.electronero.org:1122 
 * COMMANDS:     hashrate, pause, resume, quit
[2019-02-10 10:24:40] Starting thread 2/4 affined to core: #1 -> huge pages: 1/1 scratchpad: 2.0 MB
[2019-02-10 10:24:40] Starting thread 3/4 affined to core: #2 -> huge pages: 1/1 scratchpad: 2.0 MB
[2019-02-10 10:24:40] Starting thread 1/4 affined to core: #0 -> huge pages: 1/1 scratchpad: 2.0 MB
[2019-02-10 10:24:40] Starting thread 4/4 affined to core: #3 -> huge pages: 1/1 scratchpad: 2.0 MB
[2019-02-10 10:24:41] use pool pool.electronero.org:1122
[2019-02-10 10:24:41] new job from pool.electronero.org:1122 with diff 10000 and PoW msr
```
This is my config:

```
{
    "algo": "cryptonight",
    "aesni": 0,
    "threads": 0,
    "multihash-factor": 0,
    "multihash-thread-mask": null,
    "asm-optimization" : "auto",
    "background": false,
    "colors": true,
    "cpu-affinity": null,
    "cpu-priority": null,
    "donate-level": 1,
    "log-file": null,
    "max-cpu-usage": 100,
    "print-time": 60,
    "retries": 5,
    "retry-pause": 5,
    "safe": false,
    "syslog": false,
    "pow-variant" : "msr",
    "force-pow-variant" : true,
    "pools": [
        {
            "url": "pool.electronero.org:1122",
            "use-tls": false,
            "user": "f4VR74XR616Tw2wAMMfaLV1vmYBSBBbmWXBUtaV8YDb6DHsfKRoYkFaCvhPhsGDDfm1afhzLNuf5XGFmNrvodPoQ6m4q7k3qnrd4dhyK1LopQ",
            "pass": "test",
            "keepalive": true,
            "nicehash": true
        }
    ],
    "api": {
        "port": 0,
        "access-token": null,
        "worker-id": null
    },
}
```

**Comment by Miner1305** [comment]
the config you provided worked, the line "algo": "cryptonight", 
my config was algo: 0/auto

**Comment by Bendr0id** [comment]
"algo: 0/auto" doesn't exist in xmrigCC. I've never seen this before.

**Comment by Miner1305** [comment]
Following is my config and it works for everything except etnx and etnxp pools
{
  "algo": 0,
  "pow-variant": "auto",
  "aesni": 0,
  "threads": 0,
  "multihash-factor": 0,
  "multihash-thread-mask": 0,
  "background": false,
  "colors": true,
  "cpu-affinity": 0,
  "cpu-priority": 0,
  "log-file": null,
  "max-cpu-usage": 100,
  "print-time": 60,
  "retries": 5,
  "retry-pause": 5,
  "safe": false,
  "syslog": false,
  "pools": [

**Comment by djfinch** [comment]
Your algo string is wrong...
`"algo": 0`
See proper algo strings here...[WIKI](https://github.com/Bendr0id/xmrigCC/wiki/Coin-configurations#algo)

**Comment by Bendr0id** [comment]
`"algo" : 0` will work, in the case it is not able to find the algo, it will use cryptonight per default.

But this was youe issue. `"pow-variant": "auto",` it has to be `"pow-variant": "msr",` and `"force-pow-variant" : true` has to be set to mine old MSR algos.
